[2023-01-30T16:12:19.218+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.243+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.244+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.245+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:12:19.247+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.283+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-01-30 16:12:17.205977+00:00
[2023-01-30T16:12:19.292+0000] {standard_task_runner.py:55} INFO - Started process 3964 to run task
[2023-01-30T16:12:19.315+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2023-01-30T16:12:17.205977+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp50mxvcjb']
[2023-01-30T16:12:19.318+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask store_user
[2023-01-30T16:12:19.515+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2023-01-30T16:12:17.205977+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:12:19.640+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:12:17.205977+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:12:17.205977+00:00
[2023-01-30T16:12:19.644+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp.processed_user.csv
[2023-01-30T16:12:19.646+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 29, in _store_user
    filename='/tmp.processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 131, in copy_expert
    with open(filename, 'w'):
PermissionError: [Errno 13] Permission denied: '/tmp.processed_user.csv'
[2023-01-30T16:12:19.664+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20230130T161217, start_date=20230130T161219, end_date=20230130T161219
[2023-01-30T16:12:19.677+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task store_user ([Errno 13] Permission denied: '/tmp.processed_user.csv'; 3964)
[2023-01-30T16:12:19.715+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-30T16:12:19.742+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
