[2023-01-30T16:08:13.193+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-01-30T16:08:11.350676+00:00 [queued]>
[2023-01-30T16:08:13.214+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-01-30T16:08:11.350676+00:00 [queued]>
[2023-01-30T16:08:13.215+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:08:13.216+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:08:13.217+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:08:13.232+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-01-30 16:08:11.350676+00:00
[2023-01-30T16:08:13.240+0000] {standard_task_runner.py:55} INFO - Started process 3712 to run task
[2023-01-30T16:08:13.248+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2023-01-30T16:08:11.350676+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkm8ya162']
[2023-01-30T16:08:13.256+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask store_user
[2023-01-30T16:08:13.348+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2023-01-30T16:08:11.350676+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:08:13.481+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:08:11.350676+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:08:11.350676+00:00
[2023-01-30T16:08:13.484+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp.processed_user.csv
[2023-01-30T16:08:13.485+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 29, in _store_user
    filename='/tmp.processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 131, in copy_expert
    with open(filename, 'w'):
PermissionError: [Errno 13] Permission denied: '/tmp.processed_user.csv'
[2023-01-30T16:08:13.505+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20230130T160811, start_date=20230130T160813, end_date=20230130T160813
[2023-01-30T16:08:13.525+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task store_user ([Errno 13] Permission denied: '/tmp.processed_user.csv'; 3712)
[2023-01-30T16:08:13.578+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-30T16:08:13.602+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
